# Generated by Django 4.2.3 on 2023-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movcontablesdnodomici',
            fields=[
                ('idnodomiciliado', models.AutoField(db_column='idNoDomiciliado', primary_key=True, serialize=False)),
                ('movcontable_d', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Movcontable_d', max_length=10, null=True)),
                ('codunidadeconomica', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodUnidadEconomica', max_length=10, null=True)),
                ('tipodoccredfiscal', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TipoDocCredFiscal', max_length=2, null=True)),
                ('nrodocdua', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroDocDUA', max_length=45, null=True)),
                ('anioduacredfiscal', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='AnioDuaCredFiscal', max_length=4, null=True)),
                ('montoretigv', models.DecimalField(blank=True, db_column='MontoRetIGV', decimal_places=2, max_digits=18, null=True)),
                ('pais', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Pais', max_length=7, null=True)),
                ('nombrenodomiciliado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NombreNoDomiciliado', max_length=100, null=True)),
                ('rentabruta', models.DecimalField(blank=True, db_column='RentaBruta', decimal_places=2, max_digits=18, null=True)),
                ('deduccioncosto', models.DecimalField(blank=True, db_column='DeduccionCosto', decimal_places=2, max_digits=18, null=True)),
                ('rentaneta', models.DecimalField(blank=True, db_column='RentaNeta', decimal_places=2, max_digits=18, null=True)),
                ('tasaretencion', models.DecimalField(blank=True, db_column='TasaRetencion', decimal_places=2, max_digits=10, null=True)),
                ('impuestoretenido', models.DecimalField(blank=True, db_column='ImpuestoRetenido', decimal_places=2, max_digits=18, null=True)),
                ('convenio2imposicion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Convenio2Imposicion', max_length=7, null=True)),
                ('tiporenta', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TipoRenta', max_length=7, null=True)),
                ('aplicaart76', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='AplicaArt76', max_length=1, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Estado', max_length=1, null=True)),
            ],
            options={
                'db_table': 'MovContablesDNoDomici',
                'managed': False,
            },
        ),
    ]
