# Generated by Django 4.2.4 on 2023-08-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_movcontablesdnodomici'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMovimientocajac',
            fields=[
                ('idmovimientocajac', models.AutoField(db_column='idMovimientoCajaC', primary_key=True, serialize=False)),
                ('anio', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=4, null=True)),
                ('mes', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=2, null=True)),
                ('zona', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=10, null=True)),
                ('codunidadeconomica', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='codUnidadEconomica', max_length=10, null=True)),
                ('nrodoc', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroDoc', max_length=10, null=True)),
                ('fechacontable', models.DateTimeField(blank=True, db_column='FechaContable', null=True)),
                ('codmgc', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='codMGC', max_length=2, null=True)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=200, null=True)),
                ('rucemitido', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='RucEmitido', max_length=11, null=True)),
                ('codigoctabancaria', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodigoCtaBancaria', max_length=12, null=True)),
                ('codigotipodocpago', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodigoTipoDocPago', max_length=4, null=True)),
                ('nrodocpago', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroDocPago', max_length=14, null=True)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=18, null=True)),
                ('transferido', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
                ('correlativo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Correlativo', max_length=10, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Estado', max_length=1, null=True)),
                ('transferidoant', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TransferidoAnt', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_MovimientoCajaC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMovimientocajad',
            fields=[
                ('idmovimientocajad', models.AutoField(db_column='idMovimientoCajaD', primary_key=True, serialize=False)),
                ('codunidadeconomica', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodunidadEconomica', max_length=10, null=True)),
                ('nrodocumento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroDocumento', max_length=10, null=True)),
                ('fechacontable', models.DateTimeField(blank=True, db_column='FechaContable', null=True)),
                ('tipomediopago', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TipoMedioPago', max_length=3, null=True)),
                ('codpro', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=14, null=True)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=250, null=True)),
                ('flujoefectivo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FlujoEfectivo', max_length=10, null=True)),
                ('codigodocumentofuente', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodigoDocumentoFuente', max_length=2, null=True)),
                ('nrodocumentofuente', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroDocumentoFuente', max_length=14, null=True)),
                ('fechadocfuente', models.DateTimeField(blank=True, db_column='FechaDocFuente', null=True)),
                ('fechavencimiento', models.DateTimeField(blank=True, db_column='FechaVencimiento', null=True)),
                ('codigoctabancaria', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodigoCtaBancaria', max_length=12, null=True)),
                ('codcuenta', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CodCuenta', max_length=12, null=True)),
                ('impdebe', models.DecimalField(blank=True, db_column='impDebe', decimal_places=2, max_digits=18, null=True)),
                ('imphaber', models.DecimalField(blank=True, db_column='impHaber', decimal_places=2, max_digits=18, null=True)),
                ('nrooperacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroOperacion', max_length=40, null=True)),
                ('nrocheque', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NroCheque', max_length=40, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=1, null=True)),
                ('reparo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=1, null=True)),
                ('tipodoc', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TipoDoc', max_length=3, null=True)),
                ('tipooper', models.IntegerField(blank=True, db_column='TipoOper', null=True)),
                ('montoigv', models.DecimalField(blank=True, db_column='MontoIGV', decimal_places=3, max_digits=12, null=True)),
                ('montoisc', models.DecimalField(blank=True, db_column='MontoISC', decimal_places=2, max_digits=10, null=True)),
                ('montoretencion4', models.DecimalField(blank=True, db_column='MontoRetencion4', decimal_places=2, max_digits=10, null=True)),
                ('rigv', models.BooleanField(blank=True, db_column='RIgv', null=True)),
                ('afecto', models.BooleanField(blank=True, db_column='Afecto', null=True)),
                ('costearigv', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CostearIgv', max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Direccion', max_length=90, null=True)),
            ],
            options={
                'db_table': 'tbl_MovimientoCajaD',
                'managed': False,
            },
        ),
    ]
